on:
  pull_request_review:
    types: [submitted, edited, dismissed]
    
jobs:
  submitted-review:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'submitted' }}
    steps:                     
      - name: Shadow pr review
        uses: actions/github-script@v3
        with:
          script: |
            console.log('should shadow pr review here');
            console.log(context.payload);
          github-token: 1234


      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
