on:
  pull_request_review:
    types: [submitted, edited, dismissed]
    
jobs:
  submitted-review:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'submitted' }}
    steps:                     
      - name: Shadow comment review
        uses: actions/github-script@v3
        with:
          script: |
            const pullRequestNumber = context.payload.issue.number;
            console.log(pullRequestNumber);


      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
